### ISSUE TITLE
Coveralls is reporting misleading coverage

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#1085]
Issue raised by: [developer]

### What?
Coveralls is reporting in the following way.
PR opens -> First build at x% -> Push again -> Covereage changed +- y% from previous commit.
What we want (and used to have) is the coverage change of the latest commit compared with the latest master build.

### Where?
`run-test.yml`
`.coveragerc`

### Reproducible?
[Yes]
Easily reproduceable on any PR, but you can arbitrarily push a branch with a much higher coverage. Wait for the report, then decrease it by a smaller amount and you will be told the coverage has decreased despite being higher.

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by rickybassom** [comment]
This is an open issue in the coveralls repo: https://github.com/lemurheavy/coveralls-public/issues/1019

**Comment by dtasev** [comment]
I'd say change the title to "Coveralls is reporting misleading coverage %" because seeing "broken" made me worry it has stopped running at all again!
