### ISSUE TITLE
Django admin page interface sizing issue

### ISSUE THREAD

**Issue by rickybassom** [autoreduction/queue-processor#1131]
Issue raised by: developer

### What?
Pages in the Django admin interface are not visible on large browser window sizes because the menu overlaps with the actual content of the page.

For example on the notifications page:

Page content is not visible
![image](https://user-images.githubusercontent.com/5902731/108502373-9c774100-72aa-11eb-8feb-b9bb642d799c.png)

Page content is visible with a smaller window
![image](https://user-images.githubusercontent.com/5902731/108502448-b6188880-72aa-11eb-9a11-ac1ba019d05b.png)

### Where?
Django admin interface. Web app > Admin

### Reproducible?
Yes

**Comment by dtasev** [comment]
Yep I see that too, I wonder if it's missing a stylesheet or something, seems like a strange thing to break, and that's handled by Django itself..
