### ISSUE TITLE
Show better reason for "Instrument not active"

### ISSUE THREAD

**Issue by dtasev** [autoreduction/queue-processor#1176]
### What?
This can happen for instruments when the reduce.py is missing. But it's not clear when/why it happened because it looks like this:

https://user-images.githubusercontent.com/1135476/109931691-0dfaba80-7cc1-11eb-86a6-cfec0036b9b6.gif

To make the instrument paused:
- Delete the reduce.py
- Click the LOGO ! This will go to the `index` view which has the decorator to activate/disable instruments

To revert:
- Make a reduce.py
- Click the logo again

**Comment by keiranjprice101** [comment]
It is also a strange choice that this check only happens on the index page.

**Comment by dtasev** [comment]
I agree, it doesn't feel right that the web app is disabling the instrument at all.

Perhaps it should be the queue processor's job?

**Comment by keiranjprice101** [comment]
Yes this feels much more in the QPs domain,  at most it should only be able to be disabled by admin manually via WebApp but this is already possible through the admin panel I think.
