### ISSUE TITLE
Add robots.txt and sitemap

### ISSUE THREAD

**Issue by rickybassom** [autoreduction/queue-processor#1196]
Issue raised by: [developer]

### What?
I'm not sure if we want the web app to be indexed by search engines when we make the web app available outside of the firewall. A `robots.txt` file can be added to the root of the web app (`https://reduce.isis.cclrc.ac.uk/robots.txt`) to tell search engines to not crawl the whole site or certain parts of the site. [More info](https://developers.google.com/search/docs/advanced/robots/intro). A [sitemap](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap) can also be added to help with indexing.

**Comment by keiranjprice101** [comment]
@rickybassom I may be out of the loop here, but will the functionality of navigating to autoreduce webapp before logging on and being redirected to `users.facilities.rl.ac.uk` be lost? Because if not the webapp wouldnt be crawlable anyway and a robots.txt would have no benefit?
