### ISSUE TITLE
Permanently storing reduced data and meta data

### ISSUE THREAD

**Issue by Anders-Markvardsen** [autoreduction/queue-processor#12]
Issue raised by: Developer

### What?
We need to investigate a solution for permanent storage of reduced data and meta data from autoreduction. This is to work towards the future where we have searchable meta data available. This issue should deal with the design of this system which will include:
* Database schema
* Hardware solution for storage (vast amount of data)
* Interplay with autoreduction system 
  * Where do we need to make code changes
  * How do we best pull in the meta data in a appropriate format

**Comment by ElliotAOram** [comment]
Not entirely sure of the context for this @Anders-Markvardsen is this regarding storing autoreduction data + meta data long term (re. conversations we had with Tom Griffin last year)

**Comment by dtasev** [comment]
This is a good idea and a quick win would be to just copy the `reduce.py` and `reduce_vars.py` somewhere into the reduction directory on CEPH.

Considering we have so far been wiping the DB after each cycle we're very far from being reproducible, although we do store the reduce/vars scripts with #921.

Something to keep in mind is that if we just copy `reduce.py` and `reduce_vars.py` we can probably drop the Variables tables and ReducedRun.script ...
