### ISSUE TITLE
Create accessibility statement

### ISSUE THREAD

**Issue by dtasev** [autoreduction/queue-processor#1200]
Issue raised by: [developer/user/project requirement]

### What?
Create an accessibility Statement that can be accessed from anywhere on site (Link in footer maybe)

Include a way for users to contact us about accessibility (mailto link in footer maybe)

https://www.ukri.org/about-us/accessibility-statement/

https://www.isis.stfc.ac.uk/pages/accessibility.aspx

**Comment by rickybassom** [comment]
Current working branch https://github.com/ISISScientificComputing/autoreduce/tree/add-accessibility-statement

**Comment by dtasev** [comment]
What's in the working branch seems **a lot** more than what both STFC and UKRI have. We probably want to just have the same sections as those ones:
-

**Comment by dtasev** [comment]
I think our only non-accessible content is the plot images, since they're generated dynamically it would be very hard to have proper captions.

**Comment by rickybassom** [comment]
I'm basing the statement on this https://www.gov.uk/government/publications/sample-accessibility-statement/sample-accessibility-statement-for-a-fictional-public-sector-website which includes all the sections we need to have
