### ISSUE TITLE
Move source code to a single package

### ISSUE THREAD

**Issue by ElliotAOram** [autoreduction/queue-processor#160]
At some point we need to move our source code to a single package. By this I mean that the project structure should be:
* documentation
  * ...
* autoreduction
  * monitors
  * queue_processors
  * utils
  * Webapp
  * etc

This should not only make us more pythonic in structure, but also allow us the added bonus of being able to run static analysis over the whole repo more easily

**Comment by ElliotAOram** [comment]
We should experiment with this at the beginning of the development period for 18.3. As it could have far reaching hidden implications we should do it at the beginning of dev cycle and have the whole cycle to find any issues

**Comment by dtasev** [comment]
It's an ongoing slow discussion whether to go to a single package, or multiple repositories.

Regardless the structure above won't work well for Django, if we're going to a single package, we should make sure that the Django project is at the top level. That way we can get the ORM access everywhere and can remove all the orm.py stuff.
