### ISSUE TITLE
System tests for Mantid

### ISSUE THREAD

**Issue by ElliotAOram** [autoreduction/queue-processor#316]
Issue raised by: [Nick Draper]

### What?
Nick has requested if there is a way to tie in autoreduction with some form of system/acceptance testing for Mantid. After we begin collating the scripts that users are using for reduction online, I think this would be a good idea as it is mutually beneficial to both autoreduction and Mantid.

**Comment by dtasev** [comment]
This should be a lot easier with the Docker/Singularity image!
