### ISSUE TITLE
Webapp slower when clicking on individual runs

### ISSUE THREAD

**Issue by Anders-Markvardsen** [autoreduction/queue-processor#494]
Issue raised by: [developer]

### What?
Observed to 16th March 2020 (tested from laptop from home)

* clicking on instrument buttons load the page
  * OSIRIS in 5.7 seconds. In second attempt 5.75 seconds
  * MUSR in 5.3 seconds. In second attempt 5.1 seconds
  * MARI in 2.7 seconds. In second attempt 2.8 seconds
  * POLARIS in 2.2 seconds. In second attempt 1.5 seconds

* clicking on individual runs load page
  * OSIRIS 143976 in 18.8 seconds. in second attempt 20.0 seconds
  * MUSR 81934 in 22.7 seconds. in second attempt 21.7 seconds
  * MARI 27282 in 17.6 seconds. in second attempt 17.8 seconds
  * POLARIS 125701 in 16.3 seconds. in second attempt 18.6 seconds

The purpose of this issue is
  1. to understand why it takes longer to load an individual page as compared to an instrument page. Intuitively you may expect the opposite, i.e. that it should be faster to load an individual page.
  2. make it faster to load individual pages

This issue is likely a bigger task to fix.

### Where?
In conversation with Elliot he indicated that the issue could be due  many duplicates of reduction parameters and similar in database.

### How?
While doing daily checkups

### Reproducible?
Yes

### How to test the issue is resolved
Likely a webapp database instance of sufficient entries is needed to see this effect. Such may be created on the fly or by creating a testing environment against all of cycle 19_4 data. E.g. testing loading of instrument page is faster than testing individual run. If the approach is taking to create a testing environment of all of 19_4 for example, it should first be checked that it contains no sensitive information

**Comment by ElliotAOram** [comment]
As discussed before this is due us not checking variables in the database for existence before creating new ones (see #285). This is something I am planning to look into in the near future.

**Comment by dtasev** [comment]
Even with #285 done I think this is still the case - there's a good chance the querying inside the view is doing way too many DB hits and can be optimised
