### ISSUE TITLE
Create a better local development environment

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#730]
Issue raised by: [developer]

### What?
Currently a lot of work is done against the dev node. This causes a lot of problems when multiple people are making potentially breaking changes at the same time. (E.g. someone is trying to submit a run, while someone else has stopped the queue processors)

We should have a local development environment that is completely isolated, to develop on. This would require a few things:
- A useful local database that is pre-populated (Either real data or a script to generate random seeded data could be used)
- Local ActiveMQ
- Local version of CEPH 
- Local WebApp

This environment should be easy to create and setup, and should be able to be broken without fear of interfering with other peoples work.

This work would be easier to complete if the different parts of autoreduction were containerised, though it is possible to do beforehand.

#### One solution
One way to achieve this would be to use vagrant. We could provide an autoreduction vagrantfile which does the following:
- Sets up a shared directory between the guest and host, where the codebase will go
- Built from a vagrantfile that has docker
- exposes ports to host
- run the autoreduction containers

This will allow every developer to have the same environment and run autoreduction in an isolated environment with a simple `vagrant up`.

refs #586 #347

**Comment by dtasev** [comment]
> Local version of CEPH
You don't need that it will output just as fine in any folder

> a useful local DB
This is now at least easier to get with SQLite3 though we might want to consider a developer option to add a fixture so that the web app isn't absolutely empty when you make it

At's missing that you need to have a local running `queue_processor`
