### ISSUE TITLE
Create a Containerised Instance of AMQ Service for Development

### ISSUE THREAD

**Issue by JackEAllen** [autoreduction/queue-processor#743]
Issue raised by: developer

### What?
Using Docker, create a containerised instance of ActiveMQ service for development use as part of #736 
There are many existing docker images for AMQ available which can be used directly or just for reference, one of which can be found [here](https://hub.docker.com/r/rmohr/activemq)

Please ensure that you document your work in a README.md following the our project best practices found on the wiki page and/or description on documentation in issue #736 

### Where?
* autoreduction_environment/
* autoreduction_environment/amq/

### How?
A need to improve the development environment.

### How to test the issue is resolved
* Documentation is descriptive with plenty of detail and easy to follow (ask all team members to test and critique)
* Containerised AMQ service runs as expected and can be visible externally to container (incl HawtIO dashboard).

**Comment by dtasev** [comment]
This is a nice idea - we can containerise these steps:

```
python setup.py externals -s activemq
sudo python setup.py start
queue_processors/restart.sh
```
and just have a docker image that you can run with `docker run -v /path/to/queue_processor` (-v to mount the queue_processor from the local development code so that we run the version we want).
