### ISSUE TITLE
Add backup-manual-submission script, when database lookup fails

### ISSUE THREAD

**Issue by Anders-Markvardsen** [autoreduction/queue-processor#784]
Issue raised by: [developer]

### What?
Using `manual_submission.py` only needs instrument name and run number which is great. However, this relies on database lookup either available in autoreduction database or ISIS Data Catalogue. When this not available this fails.

Example of this from today is running

```
python manual_submission.py HRPD 78261
```

which resulted in output:

```
Logging into ICAT
Logging into Database
Logging into ActiveMQ
Cannot find datafile for run_number 78261 in Auto-reduction database. Will try ICAT...
Cannot find datafile 'HRP78261.nxs' in ICAT. Will try with zeros in front of run number.
Cannot find datafile 'HRP00078261.nxs' in ICAT. Exiting...
```

HRP78261.nxs is neither available in autoreduction database nor in ICAT (although it should be, but ingestion to ICAT does not always work), but it exist on the archive \\isis\inst$\NDXHRPD\Instrument\data\cycle_19_4\HRP78261.nxs.

Suggested solution: create separate manual submission script to scripts/manual_operations/manual_submission.py and call it something manual_submission_without_lookup.py. Look at monitors/run_detection.py and from that get inspiration to submitting jobs without database lookup. Also, consider looking at git history and you might be able to recover an old manual submission scripts which was setup to work this way. 

In an ideal world you would not need this, but in practice and as experience today it may be needed, and potentially in critical situations during cycles.

### How to test the issue is resolved
Add tests for this script in scripts/manual_operations/tests. Furthermore, test it manually with a number of ISIS runs; note this can be any runs including runs which already exist in database. Write documentation for this manual submission script in scripts/manual_operations/README.md and below the section that explains how operate manual_submission.py works.

**Comment by Anders-Markvardsen** [comment]
Can't submit anything with existing script after wiping it and before beta testing! Hence this has become a release requirement

**Comment by dtasev** [comment]
Would it not be better instead of having another script to just make `manual_submission` check the archive as a last resort?

**Comment by Anders-Markvardsen** [comment]
Possibly (where maybe 'reusing' ideas from https://github.com/ISISScientificComputing/autoreduce/blob/master/monitors/run_detection.py), if it is possible to do this without degrading the interface of manual_submission to become less user friendly. At the moment the manual_submissing is nice in that all that is needed is instrument name and run number. 

The purpose of manual_submission_without_lookup.py I imagine to be a very short script with near zero overlap with manual_submission.py (other than initiating connections) and requiring all the info to be explicitly provided manual, that is to send:

```
 "run_number": 51533,
 "instrument": "LARMOR",
 "rb_number": 2010389,
 "started_by": -1,
 "data": "\\\\isis\\inst$\\NDXLARMOR\\Instrument\\data\\cycle_20_2\\LARMOR00051533.nxs"
```

I.e. a last resort script that is so simply that it cannot ever fail or extremely unlikely to ever fail.

What do you think?

**Comment by Anders-Markvardsen** [comment]
Note two more example, which as of now we can now manually submit 

```
python manual_submission.py HRPD 79052
python manual_submission.py HRPD 79051
```

**Comment by Anders-Markvardsen** [comment]
Another one which can't be submitted currently with the current manual_submission script

```
python manual_submission.py GEM 89890
```

**Comment by dtasev** [comment]
Two ways come to mind, optionally append the archive path to be used:

```
python manual_submission.py INSTRUMENT RUN_NUMBER ARCHIVE_PATH
```
So it would look like

```
python manual_submission.py LARMOR 51533 \\\\isis\\inst$\\NDXLARMOR\\Instrument\\data\\cycle_20_2\\LARMOR00051533.nxs
```
by the way - can we use Unix paths to avoid having too many `\`? i.e.
```
python manual_submission.py LARMOR 51533 /isis/inst$/NDXLARMOR/Instrument/data/cycle_20_2/LARMOR00051533.nxs
```

Or we could go with explicit flags using `argparse` and have it like this:
```
python manual_submission.py LARMOR 51533 --archive-path /isis/inst$/NDXLARMOR/Instrument/data/cycle_20_2/LARMOR00051533.nxs
```

> The purpose of manual_submission_without_lookup.py I imagine to be a very short script with near zero overlap with manual_submission.py

Implementation wise we could keep them separate, but usability wise is there any reason that `manual_submission.py` shouldn't create the instrument if it doesn't exist?

**Comment by Anders-Markvardsen** [comment]
Of your suggestions I refer 

```
python manual_submission.py LARMOR 51533 --archive-path /isis/inst$/NDXLARMOR/Instrument/data/cycle_20_2/LARMOR00051533.nxs
```

since other suggestion conflicts with this existing munual_submission.py other nice feature

````
python manual_submission.py INSTRUMENT START_RUN_NUMBER END_RUN_NUMBER
````

How would you suggest best modify your `argparse` suggestion to also accommodate this use case?  

About your question "is there any reason that manual_submission.py shouldn't create the instrument if it doesn't exist?" . The answer to this is no, i.e. if the instrument does not exist in the autoreduce (mysql) database it should create an entry for it.
