### ISSUE TITLE
Autoreduction accessibility

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#786]
Issue raised by: [developer]

The WebApp must meet the accessibility regulations laid out here: https://accessibility.campaign.gov.uk/

# Identify what needs to be done.
Guidance can be found [here](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps?utm_source=CampaignPage&utm_campaign=access_regs) on what needs to be done. And for page by page assessment of accessibility within the webapp the [wave tool](https://wave.webaim.org/) can be used as well as the web content accessibility guidelines ([WCAG](https://www.w3.org/TR/WCAG21/#abstract))

# Things That Definitely Need Doing
- [x] Evaluate how accessible the WebApp currently is using tools outlined above and other is necessary
- [x] Create Issues based on the findings of the above step
- [ ] Create an accessibility Statement that can be accessed from anywhere on site (Link in footer maybe) #1200
- [ ] Create a way for users to contact us about accessibility (mailto link in footer maybe) #1200
- Make sure all new features and additions going forward are accessible. (It would be good to add a page to the wiki with guidance for future reference)

Once this campaign is better understood a more thorough roadmap can be created.

**Comment by rickybassom** [comment]
Issues based on the findings:
- HTML warnings / add accessibility tags - https://github.com/ISISScientificComputing/autoreduce/issues/759
- Contrast issues - https://github.com/ISISScientificComputing/autoreduce/issues/790

**Comment by JEThompson97** [comment]
In BusApps, we've made a Wiki which sign-posts to various requirements and tools:
https://github.com/isisbusapps/ISISBusApps/wiki/Accessibility

Not sure if permissions are required to access this wiki? If so I'm sure we can grant them for the autoreduction team.

**Comment by Anders-Markvardsen** [comment]
Note and related to making the WebApp visible outside the firewall that #927 is needed also

**Comment by rickybassom** [comment]
> Create a way for users to contact us about accessibility (mailto link in footer maybe)

@keiranjprice101 Does the mailto link that you added to the footer cover this?

**Comment by keiranjprice101** [comment]
@rickybassom I don't believe so

**Comment by rickybassom** [comment]
> @rickybassom I don't believe so

Should we add a separate mailto link that says "Contact us about accessibility" that links to the same email address?

**Comment by keiranjprice101** [comment]
@rickybassom I _think_ we need to add a mailto accessibility link, and a link to our accessibility statement page. Both in the footer

**Comment by dtasev** [comment]
Does the *Things That Definitely Need Doing* capture all that needs doing before we can close this issue?

**Comment by keiranjprice101** [comment]
@dtasev Yes, with the exception of the last one

**Comment by dtasev** [comment]
Do you know if there is a UKRI one that we can show? Or a standard statement from somewhere else?

**Comment by rickybassom** [comment]
> Do you know if there is a UKRI one that we can show? Or a standard statement from somewhere else? I see the UKRI one at https://www.ukri.org/about-us/accessibility-statement/, but I don't think we can link to it as it states "This statement applies to content published on the ukri.org domain."

There's this one https://www.isis.stfc.ac.uk/pages/accessibility.aspx but I'm not sure if it applies to Autoreduction

**Comment by keiranjprice101** [comment]
When i spoke to bisapps about this I was told that we should write our statement and have it approved by the legal team. And we can get their email address to send it to them

**Comment by rickybassom** [comment]
Can we use this https://stfc.ukri.org/about-us/accessibility/?
> This accessibility statement applies only to the Science and Technology Facilities Council websites and relates to all new and reviewed public facing websites ...
