### ISSUE TITLE
Add config for emails and urls

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#805]
Issue raised by: [developer]

### What?
Add a config that stores urls and email addresses that are commonly added to web pages. This will make it easier to change external addresses/emails in future

### Where?
Will be used in templates, but where the config will be depends on how its implemented

### How?
There are lots of urls and email adresses used multiple times in multiple templates. It would be good to centralise the values and call them by a config. 

### How to test the issue is resolved
External links and emails will be included in pages by accessing a config, and not hard coded.

**Comment by dtasev** [comment]
I'm not 100% clear which pages we want to add these emails to - is it user emails? Is it our support email?
