### ISSUE TITLE
Project name confusion: Autoreduction, Auto‑reduction or Autoreduce?

### ISSUE THREAD

**Issue by rickybassom** [autoreduction/queue-processor#807]
Issue raised by: developer

### What?
There seems to be multiple names for this project. 
* Autoreduction (most commonly used in the code base)
* Auto‑reduction (as seen on the web app)
* Autoreduce (the GitHub repository name)

### Where?
The README and codebase:
![image](https://user-images.githubusercontent.com/5902731/95596044-ca1ec480-0a44-11eb-9ee5-eff99fbc7a38.png)

---

The web app:
![image](https://user-images.githubusercontent.com/5902731/95595780-78763a00-0a44-11eb-9559-3798e935e751.png)

---

GitHub:
![image](https://user-images.githubusercontent.com/5902731/95595890-9b085300-0a44-11eb-945e-a3e032b10cbf.png)

### How to test the issue is resolved
* Decide on one name as a team and change all occurrences of the old names.

**Comment by JEThompson97** [comment]
Yes! I think this really ought to be addressed. I was never sure how to write 'auto reduction' (hyphens? spaces? capitals?) and felt it caused unnecessary confusion..

Lets pick a name and stick with it, please 😂

**Comment by JEThompson97** [comment]
Also, I think it would be good to have a decided **abbreviated** name too. "Auto reduction" is a long word, a short version would be really useful for diagrams, and conversations within the team. Business Applications have 'BusApps' for example.

'AR' should be fine but might have some confusion with _'Augmented Reality'_ outside of the team, but I don't think that matters really.
