### ISSUE TITLE
Look at database reset script

### ISSUE THREAD

**Issue by keiranjprice101** [autoreduction/queue-processor#809]
Issue raised by: [developer]

### What?
The database reset script presented me with some problems when it came to the backup part.
It wont work on linux at all.

It would be good if we could optionally pass a backup directory to the script. We also need to verify that the backup is working correctly.

### Where?
`scripts/database_management/reset_database_post_cycle.py`

### How?
Identified in #766 
### Reproducible?
[Yes]

### How to test the issue is resolved
Be able to run the script on a linux/mac machine
Be able to optionally pass the backup dir
Backup and wipe functionality works hassle free.

**Comment by dtasev** [comment]
Ideally we want to look into a way of doing this with Django, because it'll be more convenient
