### ISSUE TITLE
Queue processors don't reconnect if ActiveMQ goes down

### ISSUE THREAD

**Issue by jsws** [autoreduction/queue-processor#88]
If ActiveMQ goes down both of the queue processors will not reconnect when it comes back up, in fact they don't even realise it's gone down and will sit idle until restarted.

Useful resources to fix this: 
https://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects
https://stomp.github.io/stomp-specification-1.2.html#Heart-beating

**Comment by ElliotAOram** [comment]
This is still a problem and should be addressed
