### ISSUE TITLE
Alert developers when run_detection task fails 

### ISSUE THREAD

**Issue by dtasev** [autoreduction/queue-processor#896]
Issue raised by: [developer/user/project requirement]

### What?
Currently if an error is encountered during the execution of the run_detection script it will silently fail

We may be able to make it email a developer via this: https://superuser.com/questions/249103/make-windows-task-scheduler-alert-me-on-fail

### How to test the issue is resolved
Set-up emailing on failure of the task; ensure the emails are properly sent out and received

**Comment by Anders-Markvardsen** [comment]
A problem which highlight this issue observed this morning: "On windows utility machine noticed C:\Autoreduction\logs\run_detection.log repeated messages "ERROR - File does not exist '\\isis\inst$\NDXARGUS\Instrument\data\cycle_20_3\ARGUS00072303.nxs'". The reason for this is that ARGUS00072303 is stored in cycle 20_2 and not cycle 20_3. Fix this by updating C:\lastruns\lastruns.csv entry manually to 72303. Argus are now coming through OK: runs from 72304 are archived in \inst$\NDXARGUS\Instrument\data\cycle_20_3". It would be have been better if we had been notified about this

**Comment by dtasev** [comment]
This might be possible with https://www.elastic.co/beats/winlogbeat. 

Alternatively, and probably easier to set up, we can move the `run_detection` to Linux, make it log success/failure, install `filebeat` to ship the logs to Elastic and create an alarm for a failure. And yeah that might be easier than dealing with the `winlogbeat` & config
