### ISSUE TITLE
Use one Python version across dev servers, prod servers and Travis/GH actions

### ISSUE THREAD

**Issue by rickybassom** [autoreduction/queue-processor#916]
Issue raised by: [developer]

### What?
We appear to be using multiple different versions of Python. 

Here's what we are using across servers using `python3 --version`:
- reducedev2: v3.7.4
- reducequeuedev: v3.7.4
- reduce: v3.7.8
- autoreduce: v3.6.8

Others:
- Travis-CI: v3.7
- Wiki recommends: v3.6

### Where?
Servers: reducedev2, reducequeuedev, reduce, autoreduce
And with Travis and the wiki

### How?
Deciding a Python version to use for GH actions testing https://github.com/ISISScientificComputing/autoreduce/pull/906

### Reproducible?
[Yes]

### How to test the issue is resolved
* Agree on a Python version to use
* Use that Python version consistently

**Comment by keiranjprice101** [comment]
@dtasev Once this is decided we should probably communicate this to the devops team
