### ISSUE TITLE
remove webapp "Overwrite Previous Data" and after consultation re-add feature

### ISSUE THREAD

**Issue by Anders-Markvardsen** [autoreduction/queue-processor#956]
Issue raised by: developer and with user Tatiana

### What?
Observed that "Overwrite Previous Data" webapp feature no longer works; tested with the MARI instrument that outputs reduced files in the `flat_output_instruments` mode - regardless of what value it is set to files are in both cases are overwriten.

Reflection on on this feature and taking into account recent changes such as plotting and the two different modes of outputting reduced data, judged to be more pain than gain to re-introduce this feature as is (e.g. for non `flat_output_instruments` it seems that the value of `Overwrite Previous Data=true` is none to a user).

Hence here is an umbrella issue to remove "Overwrite Previous Data" and in steps work reintroduce it, and as discussed with Tatiana, 

- [x] #957 Remove "Overwrite Previous Data" and add webapp help doc explaining the two reduce file output structure modes `flat_output_instruments` and not ``flat_output_instruments` and their pros and cons
- [ ] Based on clear explanation of `flat_output_instruments` and not ``flat_output_instruments` modes and there proc and cons, agree with users how to re-enabled this and for which use cases and how these affects plotting of past runs etc.

**Comment by dtasev** [comment]
We should aim to do the removing part before 21_1, and the consulting part afterwards

**Comment by dtasev** [comment]
I think a question that would be useful is: would users like to overwrite a single VERSION of a reduction run? If the answer is No, this simplifies the handling a bit:

- We can remove the `flat_output_instruments` setting
- Then we can pre-set overwrite value for each instrument
- And the behaviour becomes
	- If you do not overwrite then you get the `run-version-N` folder structure
	- If you do overwrite you get the flat output structure.

For this to work we'll have to provide Instrument default overwrite value, but that could be manually overriden for a run, in case they want to compare multiple values.

There's an edge case here - if we have multiple versions & then the latest version decides to have `overwrite=True` what do we do? I'd probably go with just ignoring the other `run-version-N` folders and just save out the data in the `autoreduced/` folder, so the result structure would be like this:
```
autoreduced/
|
|--- run-version-0/ - folder containing all the reduce files
|--- run-version-1/
|--- run-version-2/
| ### user changed their mind, latest run is with `overwrite=True`
|-> the rest of the reduced files, saved out alongside the previous `run-version-N` folder
```

**Comment by Anders-Markvardsen** [comment]
@dtasev about your question "I think a question that would be useful is: would users like to overwrite a single VERSION of a reduction run?", the answer has been thus far from customers either strong preference for always overwrite previously reduced data (i.e. with flat directory structure) or never overwrite previously reduced data (i.e. for every rerun new run-version-# folder is created). Does this answer your question? 
Also, consider creating a few pictures/mock-ups for this modified user experienced both webapp and what they see on ceph, which we discuss and as relevant could also be used in consultation with customers
